common:
    lid_topic:  "/rslidar_points"
    imu_topic:  "/rslidar_imu_data_correct"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 5                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 144 
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.1

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.01
    b_gyr_cov: 0.01
    fov_degree:  120
    det_range:  30.0
    extrinsic_est_en: true # true: enable the online estimation of IMU-LiDAR extrinsic

    extrinsic_T: [ 0.0042744, -0.0157518, -0.011212]
    # extrinsic_R: [ 0.0271229, -0.9996006, -0.0079369,
    #                 0.0023410, -0.0078763, 0.9999663,
    #                 -0.9996294, -0.0271406, 0.0021264 ]
    extrinsic_R: [ 1, 0, 0,
                0, 1, 0,
                0, 0, 1]

publish:
    path_en: true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point clousd scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: 1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.